### ISSUE TITLE
Fortune sometimes prints with incorrect line breaks.

### ISSUE THREAD

**Issue by olliequ** [olliequ/KittyBot#3]
**What it should print like:**

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

**What it currently sometimes prints like:**

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed 
do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
 nisi ut aliquip ex ea commodo consequat."
 
 Here is an actual example of the error from the server: https://imgur.com/a/yJ2YbgO
 
 **Edit**: Fortunes also sometimes print with 2 spaces between sentences. Obviously, there should only be 1 whitespace. Here's an example: https://imgur.com/a/yoO9FW1

**Comment by flukiluke** [comment]
Sometimes the fortune has line breaks for wordwrapping (which should be removed) and sometimes for layout (which should not). An ML solution may be needed.

**Comment by jimbxb** [comment]
I don't think we need ML do fix this. A few simple regexes should do the trick.

`/(?![.])\s*\n/` should be able to recognise lines that are terminated early for line wrapping purposes--we can replace these with a single space.

We can also normalise spaces by replacing `/\s{2,}/` wit a single space.

**Comment by olliequ** [comment]
Fixed with 8542056755420035110dd4788088da44b967f12f.
