### ISSUE TITLE
failure to use raw ('r') strings for regex

### ISSUE THREAD

**Issue by a-lexer** [olliequ/KittyBot#45]
https://github.com/olliequ/KittyBot/blob/e8edbf3e29781c080888a58ae2885d3aa64d93e3/extensions/duplicate_message_policing.py#L53

This leads to the ugly necessity of having two backslashes \\ when only one would be needed in a raw string. i.e. r"<a?:[a-z]+:\d+>"

**Comment by flukiluke** [comment]
See also: https://github.com/olliequ/KittyBot/blob/e8edbf3e29781c080888a58ae2885d3aa64d93e3/extensions/userinfo.py#L63
