### ISSUE TITLE
Kitti does not allow duplicate Discord emoji with uppercase identifiers in duplicate message policing

### ISSUE THREAD

**Issue by a-lexer** [olliequ/KittyBot#56]
Regex at https://github.com/olliequ/KittyBot/blob/ad1997a356ca170dc66e556132e7dd75d149b09d/extensions/duplicate_message_policing.py#L54 is deficient as it does not allow :Poggers: to be resubmitted since it foolishly specifies such capacity only for lower case names. Poggers starts with an uppercase letter (hereafter referred to as 'P'). 

Critical?

**Comment by flukiluke** [comment]
Definitely critical. Can we get a patch rolled out within 24 hours?

**Comment by adamnwerbik** [comment]
Gonna need a Sunday hotfix surely

**Comment by a-lexer** [comment]
ceci n'est pas possible

requires ennui on behalf of one of the developers
