### ISSUE TITLE
Ceci n'est pas une message tally

### ISSUE THREAD

**Issue by flukiluke** [olliequ/KittyBot#60]
![emojicloud](https://user-images.githubusercontent.com/11623995/202845005-94d36268-3bb3-4367-9ff1-028c9b493119.png)

**Comment by olliequ** [comment]
Incredibly weird behaviour. When you start up the bot fresh, `/wordcloud` works as intended. If *after* that you run `/messageboard`, and then after that `/wordcloud` again, you get the error. See this in the below image.

It's as if some sort of buffer isn't clearing. I replaced `bufferr = BytesIO()` with:
```
bufferr = BytesIO()
bufferr.truncate(0)
bufferr.seek(0)
```
and still doesn't work.

![image](https://user-images.githubusercontent.com/60557827/205784326-ec69192c-1504-40f9-9138-f3dd35927278.png)

**Comment by flukiluke** [comment]
On a completely irrelevant note, there's only one r in "buffer".
