### ISSUE TITLE
Changing of image repost detection algo means 'history' of known duplicates was reset

### ISSUE THREAD

**Issue by olliequ** [olliequ/KittyBot#76]
However, the previous image hashes are `<message_id, image hash>` in the table, so they are saved. The thing is their hashes are the hashes from the old algo. This means that the new algorithm won't detect a reposted image of this old set from here on out as the new hashing algo is different to the old one -- so the same image would have 2 different hashes. 

So a script is needed to go to each old message, get the new hash (using the new hash algo) and insert it into the table. Shouldn't be too bad! I believe there's around 40 images which need a hash update.

**Comment by flukiluke** [comment]
Previous image records are no longer in the table, so this can no longer be done.
