### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by a-lexer** [olliequ/KittyBot#79]
Faster, leading to fewer wasted CPU minutes, assisting with reducing climate change.

See e.g. https://kracekumar.com/post/micro-benchmark-python-311 \
https://www.phoronix.com/review/python-311-performance

**Comment by flukiluke** [comment]
At least one blocking issue is known: the current version of hikari-toolbox does not support 3.11.

The latest commits do support it, but there has not yet been a release we can pick up.

**Comment by a-lexer** [comment]
> At least one blocking issue is known: the current version of hikari-toolbox does not support 3.11.
> 
> The latest commits do support it, but there has not yet been a release we can pick up.

https://pypi.org/project/hikari-toolbox/0.1.5/
